### ISSUE TITLE
Include columns that are not directly available in the API data

### ISSUE THREAD

**Issue by SydneyUni-Jim** [SydneyUniLibrary/print-slip-report#16]
- [x] Determine what enrichments are needed for the additional columns.
- [x] Extend the RequestedResource interface with the optional enrichments. 
- [x] Implement item enrichment.
- [x] Implement request enrichment.
- [x] Implement user enrichment.
- [x] Implement location enrichment.
- [x] Extend the column definitions to declare what enrichments are required if that column is included.
- [x] Extend the fetch pipeline to enrich the results as required for the included columns.

**Comment by SydneyUni-Jim** [comment]
## Enrichments


### Item enrichment

- [ ] Get the item via `location.copy[i].link`
- [ ] Add `resource_metadata.complete_edition` as `bib_data.complete_edition` from the item
- [ ] Add `location.copy[i].description` as `item_data.description` from the item
- [ ] Add `location.copy[i].physical_material_type` as `item_data.physical_material_type` from the item


### Request enrichment

- [ ] Get the request via `request.link`
- [ ] Replace `request.request_sub_type` with `request_sub_type` from the request
- [ ] Add `request.volume` as `volume` from the request
- [ ] Add `request.issue` as `volume` from the request
- [ ] Add `request.chapter_or_article_title` as `chapter_or_article_title` from the request
- [ ] Add `request.chapter_or_article_author` as `chapter_or_article_author` from the request
- [ ] Add `request.required_pages_range` as `required_pages_range` from the request
- [ ] Add `request.resource_sharing` as `resource_sharing` from the request.


### User enrichment

- [ ] Get the user via `request.requester.link` if it is not null
- [ ] Add `request.requester.user_group` as `user_group` from the user


### Location enrichment

- [ ] Create a locations service that gets [the locations for a particular library](https://developers.exlibrisgroup.com/alma/apis/docs/conf/R0VUIC9hbG1hd3MvdjEvY29uZi9saWJyYXJpZXMve2xpYnJhcnlDb2RlfS9sb2NhdGlvbnM=/)
- [ ] Cache the locations in memory (without persistence)
- [ ] Get the location for `location.shelving_location`
- [ ] Replace `location.shelving_location` with `{ code, name }` from the location


### Resource sharing requests

- [ ] Create a lending requests service the gets [the lending requests for a particular library](https://developers.exlibrisgroup.com/alma/apis/docs/tasklists/R0VUIC9hbG1hd3MvdjEvdGFzay1saXN0cy9ycy9sZW5kaW5nLXJlcXVlc3Rz/)
- [ ] Cache the lending requests in memory (without persistence)
- [ ] Get the lending request for `request.destination.value` and `request.resource_sharing.id` if `request.request_sub_type.value` starts with `RESOURCE_SHARING`
- [ ] Add `reqiest.resource_sharing.volume` as `volume` from the lending request

**Comment by SydneyUni-Jim** [comment]
While there is a volume and issue field in a request record, it looks like that is generally — if not always — blank and the volume and issue fields are actually coming from the item record.

If the volume or issue fields are not blank in the request record, we'll use them. Otherwise, we'll take them from the item record.

**Comment by SydneyUni-Jim** [comment]
@d22 Can you confirm where the volume and issue values you see in your slip reports is coming from? Do you also see that «Enumeration A» field of the item record goes into the volume column and «Chronology I» also from the item record goes into issue column?

This is the behaviour I'm observing from my Alma. Not that it makes sense for «Chronology I» to go into the issue column. It would have make more sense to be me if it had of been «Enumeration B».

**Comment by d22** [comment]
@SydneyUni-Jim, yes, I can confirm that. Volume is `'enumeration_a'` and Issue is `'chronology_i'`. It seems a to be wrong, but I talked to some colleagues who actually use the report, they said the values as Alma provides them are useful to them as they are.
So it seems it makes sense to do the same as Alma does.

**Comment by SydneyUni-Jim** [comment]
The «Resource Sharing Volume» column is unreliable. See #43.

**Comment by SydneyUni-Jim** [comment]
The columns missing are:
- Accession Number
- Course Codes
- Process Date

**Comment by SydneyUni-Jim** [comment]
@d22 I've merged the code for this into the develop branch. Are you in a position to be able to test it out locally against your institution?

**Comment by SydneyUni-Jim** [comment]
I added the Accession Number column from the holding data that is available in an item object.

**Comment by d22** [comment]
Hi @SydneyUni-Jim, thanks a lot for the implementation of this feature! I tested it against our productive environment and so far it looks very good. The only issue I found (#45) is already fixed.

**Comment by d22** [comment]
Hi @SydneyUni-Jim, what do you think, is this ready to release? If so, we could start using it and see how it works in production. Tell me if there is anything I can help you with!

**Comment by SydneyUni-Jim** [comment]
Hi @d22, I just put in some final pieces (#47). I'm going to draw a line and say this is ready for production.
