### ISSUE TITLE
Style the report

### ISSUE THREAD

**Issue by SydneyUni-Jim** [SydneyUniLibrary/print-slip-report#19]

**Comment by ctantri** [comment]
I tried to make the font match the style guide, but aside from that the guide doesn't cover tables as far as I can see. Does this look easy to read or does it need a bit more padding? This is the HTML display though. I think I need to print it out when I get to the office tomorrow to see whether the font size is too big on paper.

![image](https://user-images.githubusercontent.com/19617370/111892374-07a16800-8a4f-11eb-8e5f-3be738c028ed.png)
