### ISSUE TITLE
Not working in Firefox - print window pop-up blocked

### ISSUE THREAD

**Issue by ctantri** [SydneyUniLibrary/print-slip-report#28]
The print window pop-up is blocked by default by Firefox, and the message that alerts the user is displayed for only half a second, so it may appear to the user as if the app has crashed.

**Comment by SydneyUni-Jim** [comment]
My Firefox also blocked the pop up. I got a yellow banner across the page saying "Firefox prevented this site from opening a pop-up window". However the app pane didn't close from me. It stayed open and I see the alert "Your browser prevented the popup that has the report from appearing".

From the Preferences button in the yellow banner, if I choose to show the popup a popup window does appear. But it has the app pane in it and not the report.

If I choose to allow popups from localhost, a popup window does appear. But again it shows the app pane and not the report. However if I click the print button in the app pane again, the popup does show and the popup does have the report printing.

If I choose to now show the yellow banner when popups are blocked, I still see the alert and the app pane still does not disappear.

**Comment by ctantri** [comment]
The app worked normally after I added it to the exceptions list in Options > Privacy & Security > Permissions. Is this something we can get around, or do we have to have a message in the app for Firefox users?

**Comment by SydneyUni-Jim** [comment]
I notice that I had an except for Alma itself in my Firefox options. Perhaps Alma itself also encounters this issue?

I didn't have the same window.open options in the code as the other cloud apps have. I tried using exactly the same code, and it didn't matter.

The Print Bib records cloud app (whose code I copied) does not have its pop up window blocked.

**Comment by SydneyUni-Jim** [comment]
The difference between the Print Bib Records cloud app and Print Slip Report is when they try to open the popup window. Print Bib Records opens the popup window within the handler for the button click. Whereas Print Slip Report needs to make a network request before it's ready to open the popup window, and so it opens it in a later event cycle.

So it looks like Firefox allows popups when they're opened in the same event cycle as a user interaction.

**Comment by ctantri** [comment]
I tested both our app and Print Bib Records after removing the exception. Print Bib Records does not have its pop up window blocked, but our app does. I noticed that the Print Bib Records pop up window only displays the HTML, but ours comes with the print dialog. I don't know whether that would make any difference - probably not, and it's to do with the event cycle as you said above.

**Comment by ctantri** [comment]
Print Bib Records displays the table in the app as a preview before the user clicks on the print button, but only the last checked item. I guess they're able to do this because they can access what's on the page, and the data is already there. Should we have a retrieve button aside from the print button?

**Comment by SydneyUni-Jim** [comment]
Worked around this by opening the popup early. It shows a "Please wait..." message until the report is generated.

**Comment by ctantri** [comment]
Tested. This resolves the issue for me.
